# Generated by Django 3.0.8 on 2020-08-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('choice_1', models.CharField(max_length=50)),
                ('choice_2', models.CharField(max_length=50)),
                ('choice_3', models.CharField(max_length=50)),
                ('choice_4', models.CharField(max_length=50)),
                ('correct_answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField()),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=200)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quiz_Questions', to='Quiz.Question')),
            ],
        ),
    ]
